/**
 * Entdecker Weine Gladbeck – Weinliste
 * Automatisch generiert aus der Produktliste (Stand: Oktober 2025)
 * Kategorien: rotwein | weisswein | rose | schaumwein | spirituosen | feinkost
 */
window.WEINE_DATA = {
  rotwein: [
    {name: '2R Dornfelder', price: 9.0},
    {name: 'Abthof Auftakt', price: 14.0},
    {name: 'Alma de Forcada', price: 35.0},
    {name: 'Anciens Temps', price: 7.5},
    {name: 'Ansitz Waldg. Mirell', price: 42.0},
    {name: 'Ansitz Waldgries St. Magdalener', price: 14.5},
    {name: 'Auftakt Monarch Reserve', price: 22.0},
    {name: 'Benjamin', price: 10.0},
    {name: 'Bibbiano Chianti Classico', price: 18.0},
    {name: 'Bibbiano Chianti Classico Reserve', price: 29.0},
    {name: 'Bretz Regent', price: 9.0},
    {name: 'Bretz Spätburgunder', price: 17.0},
    {name: 'Bretz St Laurent', price: 12.5},
    {name: 'Brunito', price: 9.0},
    {name: 'Cal y Canto', price: 5.3},
    {name: 'Caprasia Bobal', price: 15.0},
    {name: 'Chateau Magondeau Beau Site', price: 17.5},
    {name: 'Chateau Magondeau Fronsac', price: 14.0},
    {name: 'Chateau Magondeau Passion', price: 26.5},
    {name: 'Chateau Saint Ange', price: 21.0},
    {name: 'Chateau Tour Boisée Marie Claude', price: 15.0},
    {name: 'Chateau Vignol Louisiane', price: 9.5},
    {name: 'Ciu Ciu Esperanto', price: 29.0},
    {name: 'Ciu Ciu Piceno', price: 8.5},
    {name: 'Ciu Ciu San Carro', price: 13.0},
    {name: 'De Stefani Solèr', price: 21.0},
    {name: 'Diehl Rotwein', price: 7.9},
    {name: 'Domaine Combe Juliere Cuvee Aimé', price: 22.0},
    {name: 'Domaine Fichet Pinot Noir', price: 15.0},
    {name: 'Domaine Tour Boisée 1905', price: 13.0},
    {name: 'Domaine Tour Boisée Amuse Bouche', price: 8.0},
    {name: 'Domaine Tour Boisée Carignan', price: 11.0},
    {name: 'Feudo Luparello Nero d´Avola-Syrah', price: 9.5},
    {name: 'Feudo Luparello Noto', price: 13.0},
    {name: 'Flor de Morca', price: 11.0},
    {name: 'Forster Frühburgunder', price: 12.5},
    {name: 'Forsters Rotwein', price: 8.5},
    {name: 'Goswin Lambrich Spätburgunder', price: 13.5},
    {name: 'Herencia de Baco Vendimia', price: 9.0},
    {name: 'Histor.Rebsorten Süssschwarz', price: 14.0},
    {name: 'Honoro Vera', price: 7.0},
    {name: 'Jordan Cuvée 1858', price: 13.0},
    {name: 'Jordan Zweigelt Große Reserve', price: 54.0},
    {name: 'Jordan Zweigelt Pulkau', price: 14.0},
    {name: 'Kaiserbaum Gerald 1,5l', price: 35.0},
    {name: 'Karle Spätburg. halb', price: 10.5},
    {name: 'Karle Spätburgunder trocken', price: 10.5},
    {name: 'Kiefer Poetry', price: 11.5},
    {name: 'Kiefer Poetry Magnum', price: 24.0},
    {name: 'Kiefer Spätburgunder Liter', price: 7.9},
    {name: 'Kiefer Spätburgunder Prachtstück', price: 16.5},
    {name: 'Kreuzber Sonnenberg GG', price: 46.0},
    {name: 'Kreuzberg Cuvée Noir', price: 11.0},
    {name: 'Kreuzberg Frühburgunder', price: 19.0},
    {name: 'Kreuzberg Hardtberg GG', price: 49.0},
    {name: 'Kreuzberg Jraaduss', price: 8.5},
    {name: 'Kreuzberg Silberberg GG', price: 46.0},
    {name: 'Kreuzberg unplugged', price: 19.0},
    {name: 'Kreuzberg Walporzheim 1,5l', price: 64.5},
    {name: 'Kreuzberg Walporzheimer', price: 29.0},
    {name: 'Kurtatsch Lagrein Riverva', price: 28.0},
    {name: 'La Forcada Graciano', price: 17.5},
    {name: 'Le Petit Vin des Bosquets', price: 13.0},
    {name: 'Linteo Appassimento', price: 9.0},
    {name: 'Linteo Primitivo Puglia', price: 9.0},
    {name: 'Lost Boys', price: 10.0},
    {name: 'Lost Boys Magnum', price: 22.0},
    {name: 'Madonna Vittorie Lagrein', price: 14.0},
    {name: 'Madonna Vittorie Teroldego', price: 14.0},
    {name: 'Mauro Molino Barolo', price: 42.0},
    {name: 'Nals Margreid Lagrein', price: 17.0},
    {name: 'Nals Margreid Pfeffersburger', price: 12.0},
    {name: 'Paiva 56 B', price: 15.0},
    {name: 'Pozo de Nieve', price: 8.5},
    {name: 'Quinta da Oliveirinha', price: 26.0},
    {name: 'San Marzano Primitivo', price: 8.0},
    {name: 'San Marzano Primitivo SUD', price: 12.5},
    {name: 'Scherr Merlot', price: 12.0},
    {name: 'Schmitges Edition Rot', price: 10.5},
    {name: 'Sol I Graciano', price: 8.5},
    {name: 'Tenuta Tenaglia 1930', price: 36.0},
    {name: 'Tenuta Tenaglia Bricco', price: 13.0},
    {name: 'Tenuta Tenaglia Cappella III', price: 13.0},
    {name: 'Tenuta Tenaglia Giorgio', price: 18.5},
    {name: 'Tenuta Tenaglia Grignolino', price: 13.0},
    {name: 'Tommasi  Amarone', price: 42.0},
    {name: 'Torre Auriculus', price: 29.0},
    {name: 'Torre Limiti', price: 26.0},
    {name: 'Torre Piedirosso', price: 11.0},
    {name: 'Tresmatas Crianza', price: 18.0},
    {name: 'Tresmatas Reserva', price: 32.0},
    {name: 'Vegantigua', price: 11.0},
    {name: 'Vinha Paz', price: 12.5},
    {name: 'Vinha Paz Reserva 2017', price: 32.0},
    {name: 'Zotz Spätburgunder Alte Rebe', price: 12.0}
  ],
  weisswein: [
    {name: 'Abthof Beerenauslese', price: 19.0},
    {name: 'Abthof Gelber Orleans', price: 13.5},
    {name: 'Abthof Muscaris', price: 11.0},
    {name: 'Abthof Solaris', price: 11.0},
    {name: 'Abthof Souvignier Gries Fumé', price: 19.0},
    {name: 'Abthof Souvignier Gris', price: 11.0},
    {name: 'Anciens Temps Réserve', price: 10.0},
    {name: 'Anciens Temps S.bl/Ch', price: 7.0},
    {name: 'Auftakt Calardis Blanc', price: 9.0},
    {name: 'Becker Grauer Burgunder', price: 9.0},
    {name: 'Becker Sommer-Cuvée', price: 9.0},
    {name: 'Becker Weißer Burgunder', price: 9.0},
    {name: 'Becker Würzer', price: 9.0},
    {name: 'Bretz Sauvignon Blanc', price: 11.0},
    {name: 'Chateau Tour Boisée Mariette Frederique', price: 11.0},
    {name: 'Chateau Vignol Doux', price: 7.5},
    {name: 'Chateau Vignol Entre deux mers', price: 8.5},
    {name: 'Ciu Ciu Merlettaie', price: 12.0},
    {name: 'D\'Ibry Chardonnay', price: 10.0},
    {name: 'D\'Ibry Muscat Sec', price: 10.0},
    {name: 'Da Vinci Trebbiano', price: 9.5},
    {name: 'Domaine Fichet Mâcon Village', price: 13.5},
    {name: 'Domaine Tour Boisée Viognier', price: 10.0},
    {name: 'Drouard Muscadet', price: 10.0},
    {name: 'Flor de Baco Sauvignon Blanc', price: 8.0},
    {name: 'Forster Bergsteiger', price: 14.5},
    {name: 'Forster Grauburgunder Reserve', price: 19.5},
    {name: 'Forster Himmelsstürmer', price: 14.5},
    {name: 'Forster Kabinett', price: 10.0},
    {name: 'Forster Riesling feinherb', price: 9.5},
    {name: 'Forster Riesling tr.', price: 9.5},
    {name: 'Forster Seefahrer', price: 14.5},
    {name: 'Forster Solaris Auslese edelsüß', price: 12.5},
    {name: 'Forster Weißburgunder', price: 9.5},
    {name: 'Forsters Scheurebe', price: 9.0},
    {name: 'Frühlingsflirt', price: 6.5},
    {name: 'Goswin Lambrich St. Martinsberg Spätlese', price: 14.9},
    {name: 'Grachies Côtes de Gascogne', price: 6.5},
    {name: 'Gutzler Moorstein Riesling', price: 39.0},
    {name: 'Histor. Rebsorten Bormeo Verd', price: 13.0},
    {name: 'Histor. Rebsorten Grünedel', price: 15.0},
    {name: 'Histor. Rebsorten Weißer Traminer', price: 13.0},
    {name: 'Johannisberg Gelblack feinherb', price: 19.0},
    {name: 'Jordan Blanc de Noir', price: 13.0},
    {name: 'Jordan Grüner Veltliner Alte Rebe', price: 24.0},
    {name: 'Jordan Grüner Veltliner Pulkau', price: 11.0},
    {name: 'Jordan Grüner Veltliner Simone', price: 13.0},
    {name: 'Jordan Riesling vom Urgestein', price: 14.0},
    {name: 'Jordan SteinZeit', price: 54.0},
    {name: 'Kaiserbaum Rieslaner BA', price: 27.5},
    {name: 'Karle Gewürztraminer', price: 11.0},
    {name: 'Karle Grauburgunder', price: 10.0},
    {name: 'Karle Muskateller halbtrocken', price: 10.0},
    {name: 'Karle Ruländer Kabinett', price: 10.0},
    {name: 'Kiefer BA Grauburgunder', price: 16.0},
    {name: 'Kiefer Den Tag versuessen', price: 7.5},
    {name: 'Kiefer Grauburgunder Liter', price: 8.0},
    {name: 'Kiefer Herrenbuck Grauburgunder', price: 9.5},
    {name: 'Kiefer Rivaner feinherb', price: 6.5},
    {name: 'Kurtatsch Kofl', price: 23.0},
    {name: 'Kurtatsch Pinot Bianco', price: 12.5},
    {name: 'La Mateo Blanco', price: 24.0},
    {name: 'Lambrich Blanc de Noir', price: 10.5},
    {name: 'Lambrich Blauschiefer', price: 15.5},
    {name: 'Lambrich Roter Riesling', price: 15.5},
    {name: 'Lambrich St.Wernerberg', price: 20.5},
    {name: 'Le Morette Lugana', price: 13.5},
    {name: 'Letargo', price: 8.0},
    {name: 'Limne Lugana', price: 14.5},
    {name: 'Lösskindle Souvignier Gris', price: 16.0},
    {name: 'Luparello Grillo Viognier', price: 9.5},
    {name: 'Madonna Vittorie Maserà', price: 35.0},
    {name: 'Madonna Vittorie Norea', price: 16.0},
    {name: 'Madonna Vittorie Nosiola', price: 14.0},
    {name: 'Martin Darting Kerner-Riesling', price: 27.0},
    {name: 'Martin Darting Sauvignac', price: 16.0},
    {name: 'Martin Darting Spicy Orange', price: 27.0},
    {name: 'Mauro Molino Roero Arneis', price: 19.0},
    {name: 'Monbazillac Domaine de Montlong', price: 13.0},
    {name: 'Nals Margreid Gewürztraminer', price: 18.0},
    {name: 'Paiva Semiodulce', price: 7.5},
    {name: 'Pic Pool Party', price: 10.0},
    {name: 'Quinta da Raza Avesso', price: 11.0},
    {name: 'Raza Vinho Verde branco', price: 6.5},
    {name: 'San Michelin Gorgo', price: 12.5},
    {name: 'Sauternes Chateau Roumieu', price: 17.0},
    {name: 'Scherr Chardonnay feinherb', price: 9.0},
    {name: 'Scherr Gewürztr.', price: 9.5},
    {name: 'Scherr Grauburgunder', price: 9.0},
    {name: 'Scherr Ida Scheurebe', price: 9.5},
    {name: 'Scherr Müller- Thurgau feinherb', price: 6.0},
    {name: 'Scherr Muskateller', price: 9.0},
    {name: 'Scherr Riesling trocken', price: 6.5},
    {name: 'Scherr Sappalott', price: 9.0},
    {name: 'Scherr Scheurebe mild', price: 6.5},
    {name: 'Scherr Scheurebe tr.', price: 9.0},
    {name: 'Schloss Johannisberg Bronzelack', price: 31.0},
    {name: 'Schloss Johannisberg Gelblack', price: 19.0},
    {name: 'Schloss Johannisberg Silberlack', price: 59.0},
    {name: 'Schmidt Lösskindl Cabernet Blanc', price: 16.0},
    {name: 'Schmidt Müller Thurgau- CB', price: 9.0},
    {name: 'Schmidt Souvignier Gris', price: 10.5},
    {name: 'Schmitges Quereinsteiger', price: 11.0},
    {name: 'Schmitges Riesling Grauschiefer', price: 11.0},
    {name: 'Schmitges Riesling Vom Berg', price: 11.0},
    {name: 'Schmitges Rivaner trocken', price: 8.5},
    {name: 'Schmitges Treppchen GG', price: 30.0},
    {name: 'Schmitges Weißburgunder', price: 10.5},
    {name: 'Schwane Bacchus', price: 9.5},
    {name: 'Schwane Silvaner', price: 9.5},
    {name: 'Schwane Silvaner GG', price: 29.0},
    {name: 'Schwane Sylvaner Urtyp', price: 16.0},
    {name: 'Schwane Weißburgunder', price: 9.5},
    {name: 'Solo I Cayetana', price: 7.0},
    {name: 'Streda Vermentino', price: 17.5},
    {name: 'Tenuta Tenaglia Otium', price: 12.0},
    {name: 'Torre Fiano', price: 10.0},
    {name: 'Tour de Calens Graves', price: 13.0},
    {name: 'Vernaccia di San Gimignano', price: 11.0},
    {name: 'Villa Solais Vermentino', price: 9.5},
    {name: 'Villata', price: 13.0},
    {name: 'Vin Jaune', price: 49.0},
    {name: 'Vina Buron Verdejo Viura', price: 7.0},
    {name: 'Zotz GWG', price: 11.0},
    {name: 'Zotz Maltesergarten Chasselas', price: 15.5},
    {name: 'Zotz Roter Gutedel', price: 8.5},
    {name: 'Zotz Weisser Burgunder Alte Reben', price: 12.0},
    {name: 'Zotz Weißer Gutedel feinherb', price: 8.0},
    {name: 'Zotz Weißer Gutedel trocken', price: 8.0}
  ],
  rose: [
    {name: 'Chateau de la Coulerette Rosé', price: 11.0},
    {name: 'Chateau Tour Boisée Pech Majou', price: 9.0},
    {name: 'De Stefani Rosé', price: 11.5},
    {name: 'De Stefani Rosé Magnum', price: 25.0},
    {name: 'Forster Spätburgunder Rosé', price: 9.5},
    {name: 'Karle Weißherbst Liter', price: 8.5},
    {name: 'Kiefer Schmetterlinge im Bauch', price: 8.0},
    {name: 'Kiefer Tanz -Vulkan', price: 8.0},
    {name: 'Lambrich rose', price: 9.0},
    {name: 'Madonna Vittorie Kretzer', price: 14.0},
    {name: 'Magondeau Rosé', price: 9.5},
    {name: 'Pinky the Kinky', price: 9.5},
    {name: 'Scherr Schwarzriesling', price: 8.0},
    {name: 'Schmidt Spätburgunder Rosé', price: 9.5}
  ],
  schaumwein: [
    {name: 'Abthof Gelber Orleans', price: 19.0},
    {name: 'ARLENOBLE 2012', price: 69.0},
    {name: 'ARLenoble Chouilly', price: 79.0},
    {name: 'ARLENOBLE Riche', price: 45.0},
    {name: 'Auftakt Muscaris Secco', price: 11.0},
    {name: 'Da Vinci Spumante', price: 12.0},
    {name: 'Fallet Dart Ecocene', price: 59.0},
    {name: 'Fallet Dart Grande Sélection brut', price: 38.0},
    {name: 'Fallet Dart Quercus', price: 69.0},
    {name: 'Forster Furore', price: 45.0},
    {name: 'Forster Riesling Sekt Brut', price: 15.0},
    {name: 'Goswin Lambrich Pinot Blanc', price: 17.0},
    {name: 'Goswin Lambrich Riesling Brut', price: 15.5},
    {name: 'Histor. Rebsorten Blauer Muskateller', price: 12.0},
    {name: 'Jordan Veltliner Brut', price: 26.5},
    {name: 'Karle Secco Rosé', price: 9.9},
    {name: 'Kiefer Sauvignon Blanc', price: 13.5},
    {name: 'Koch Crémant d\'Alsace Tradition', price: 16.0},
    {name: 'Koch Crémant Rosé', price: 16.5},
    {name: 'Madonna Vittorie Trento DOC', price: 26.0},
    {name: 'Medici Ermete Concerto', price: 12.0},
    {name: 'Medici Ermete Gran Concerto Brut', price: 19.0},
    {name: 'Moscato D´Asti', price: 10.0},
    {name: 'Nou', price: 17.0},
    {name: 'Nou Rosé', price: 19.0},
    {name: 'Paiva Brut nature', price: 12.5},
    {name: 'Paiva Brut nature Reserva', price: 15.0},
    {name: 'Perrier Belle Epoque Set', price: 185.0},
    {name: 'Phermento Medici Ermete', price: 12.0},
    {name: 'Ponte Prosecco', price: 11.0},
    {name: 'Ponte Prosecco Rosé', price: 12.0},
    {name: 'Ponte Vino Frizzante', price: 6.5},
    {name: 'Raumland Ancestrale Fleur', price: 19.9},
    {name: 'Raumland Blanc de Blanc', price: 72.0},
    {name: 'Raumland Katharina', price: 27.5},
    {name: 'Raumland Kirchenstück', price: 39.0},
    {name: 'Reinecker Baden Cremant', price: 16.0},
    {name: 'Reinecker Chardonnay', price: 21.0},
    {name: 'Reinecker Cuvée Reserve', price: 28.0},
    {name: 'Reinecker Pinot Noir', price: 25.0},
    {name: 'Reinecker Rosé', price: 18.0},
    {name: 'Rémy Massin Blanc', price: 35.0},
    {name: 'Rémy Massin Rosé', price: 39.0},
    {name: 'Sassy Cidre Brut', price: 8.9},
    {name: 'Sassy Cidre Rosé', price: 8.9},
    {name: 'Sassy Rosé 330ml', price: 3.9},
    {name: 'Scherr Muskateller Sekt', price: 14.0},
    {name: 'Vaux Assmannshäuser Pinot Noir', price: 40.0},
    {name: 'Vaux Blanc de Noir', price: 20.0},
    {name: 'Vaux Cuvée Magnum', price: 34.0},
    {name: 'Vaux Cuvée Vaux', price: 18.0},
    {name: 'Vaux Grüner Veltliner', price: 28.0},
    {name: 'Vaux l`Artiste', price: 35.0},
    {name: 'Vaux Rosé', price: 20.0},
    {name: 'Vaux Rosé 0,375', price: 14.0},
    {name: 'Vaux Rosé Magnum', price: 38.0}
  ],
  spirituosen: [
    {name: 'A.H.Riise Ambre d\'or', price: 54.0},
    {name: 'A.H.Riise Non plus', price: 95.0},
    {name: 'A.H.Riise Reserve Superior Cask', price: 45.0},
    {name: 'A.H.Riise XO Port', price: 59.0},
    {name: 'Amerie', price: 19.0},
    {name: 'Andrea da Ponte Grappa', price: 35.0},
    {name: 'Andrea da Ponte Grappa 5cl', price: 7.5},
    {name: 'Bellabomba 0,2l', price: 8.0},
    {name: 'Bellabomba 0,5', price: 14.0},
    {name: 'Bellabomba 1 Liter', price: 22.9},
    {name: 'Bellabomba 5cl', price: 3.9},
    {name: 'Bisquit VSOP Cognac', price: 65.0},
    {name: 'Chateau du Breuil', price: 27.0},
    {name: 'Chateau du Breuil 15', price: 64.0},
    {name: 'Chateau du Breuil 30y', price: 235.0},
    {name: 'Chateau du Breuil 8 ans', price: 47.5},
    {name: 'Coretto', price: 3.9},
    {name: 'East India Madeira 10 years', price: 29.5},
    {name: 'Ehringhausen RED', price: 35.0},
    {name: 'Fernando de Castilla Amontillado', price: 17.0},
    {name: 'Fernando de Castilla Antique PX', price: 47.5},
    {name: 'Fernando de Castilla Fino', price: 17.0},
    {name: 'Fernando de Castilla Oloroso', price: 17.0},
    {name: 'Fernando de Castilla Olorosso', price: 38.0},
    {name: 'Fernando de Castilla PX', price: 21.5},
    {name: 'Fernando de Castilla Solera Reserva Brandy', price: 29.0},
    {name: 'Geiger Apfel im Holz 0,5', price: 27.0},
    {name: 'Geiger Apfel im Holzfass', price: 11.0},
    {name: 'Geiger Brennkirsche', price: 11.0},
    {name: 'Geiger Fruchtvoll Quitte 0,5', price: 26.5},
    {name: 'Geiger Gaishirte 0,1', price: 11.0},
    {name: 'Geiger Gin', price: 44.5},
    {name: 'Geiger Mirabelle 0,1', price: 9.5},
    {name: 'Geiger Mirabelle 0,5', price: 25.0},
    {name: 'Geiger Obstbrandcuvee', price: 29.5},
    {name: 'Geiger Obstbrandcuvee 0,1', price: 11.0},
    {name: 'Geiger Palmsche Birne 0,1', price: 9.0},
    {name: 'Geiger Quittenlikör', price: 9.5},
    {name: 'Gincello', price: 35.0},
    {name: 'Hampden Rum', price: 69.0},
    {name: 'High Croft', price: 39.0},
    {name: 'Hills & Harbour Orange', price: 42.0},
    {name: 'Hills&Harbour Gin', price: 42.0},
    {name: 'Jivaeri Ouzo', price: 24.0},
    {name: 'Johannsen Vanille-Rum 0,04', price: 4.5},
    {name: 'Johannsen Vanille-Rum 0,2', price: 12.0},
    {name: 'Justino’s Madeira 1999', price: 45.0},
    {name: 'Justino´s Madeira 2008', price: 42.0},
    {name: 'Kyrö Gin', price: 35.0},
    {name: 'Kyrö Pink Gin', price: 32.0},
    {name: 'Lombardo Marsala', price: 19.9},
    {name: 'Lussa Gin', price: 42.0},
    {name: 'Marzadro Affina', price: 175.0},
    {name: 'Marzadro Alpina Melone', price: 22.0},
    {name: 'Marzadro Anfora', price: 35.0},
    {name: 'Marzadro Arancello', price: 22.0},
    {name: 'Marzadro Botte Porto 0,7', price: 47.0},
    {name: 'Marzadro Botte Rum 0,7', price: 47.0},
    {name: 'Marzadro Botte Whisky 0,7', price: 47.0},
    {name: 'Marzadro Crema Limone', price: 22.0},
    {name: 'Marzadro Crema Marzapane', price: 22.0},
    {name: 'Marzadro Diciotto Lune 0,2', price: 14.0},
    {name: 'Marzadro Diciotto Lune 0,5', price: 29.0},
    {name: 'Marzadro Diciotto Lune 0,7', price: 36.0},
    {name: 'Marzadro Diciotto Lune 4cl', price: 3.9},
    {name: 'Marzadro Espressione Futura', price: 79.0},
    {name: 'Marzadro Giare Amarone', price: 49.5},
    {name: 'Marzadro Giare Chardonnay', price: 49.5},
    {name: 'Marzadro Giare Set', price: 54.0},
    {name: 'Marzadro Olia del Garda 0,7', price: 36.0},
    {name: 'Marzadro Olia del Garda 5cl', price: 3.9},
    {name: 'Marzadro Pistacchio', price: 24.0},
    {name: 'Marzadro Pistacchio 20 cl', price: 9.0},
    {name: 'Marzadro Rivera Limoni', price: 21.0},
    {name: 'Marzadro Rivera Limoni 0,2', price: 9.0},
    {name: 'Marzadro Riviera Limoni', price: 3.9},
    {name: 'Marzadro Trentina Morbida 0,7', price: 28.0},
    {name: 'Meyer Framboise', price: 45.0},
    {name: 'Meyer Mirabelle', price: 36.0},
    {name: 'Meyer Poire', price: 39.0},
    {name: 'Meyer Poire Grande Reserve', price: 45.0},
    {name: 'Meyer Vieille Prune', price: 36.0},
    {name: 'Monnet VS', price: 36.0},
    {name: 'Monnet VSOP', price: 49.0},
    {name: 'Monnet XO', price: 135.0},
    {name: 'Nadar Gin', price: 45.0},
    {name: 'Nobeltje Likör 0,7', price: 19.0},
    {name: 'Nobeltje Likör 1l', price: 25.0},
    {name: 'Olia del Garda 0,2', price: 14.0},
    {name: 'Ornabrak Gin', price: 42.0},
    {name: 'Pampero Aniversario', price: 26.5},
    {name: 'Pastis 51', price: 21.0},
    {name: 'Pastis Henri Bardouin', price: 27.5},
    {name: 'Pistacchio 5cl', price: 3.9},
    {name: 'Polignac Cognac', price: 33.0},
    {name: 'Presidendial Porto 10 Years', price: 38.0},
    {name: 'Presidental Porto Special Tawny Reserve', price: 24.0},
    {name: 'Presidential 30y', price: 109.0},
    {name: 'Presidential Porto 1995', price: 49.0},
    {name: 'Presidential Porto 20y', price: 69.0},
    {name: 'Presidential Porto Colheita 1990', price: 65.0},
    {name: 'Presidential Porto Late Bottled Vintage', price: 22.9},
    {name: 'Presidential Porto Ruby', price: 17.0},
    {name: 'Presidential Porto Tawny', price: 17.0},
    {name: 'Presidential White Porto', price: 17.0},
    {name: 'Prinz Hausschnaps', price: 18.0},
    {name: 'Prinz Rum Coconut', price: 15.0},
    {name: 'Riise Blue Line', price: 57.0},
    {name: 'Riise Family Reserve', price: 59.0},
    {name: 'Rodnik`s Absinth', price: 19.9},
    {name: 'Sasse Alte Marille', price: 27.5},
    {name: 'Sasse Haselnuss', price: 27.5},
    {name: 'Sasse Haselnuss 0,5', price: 17.5},
    {name: 'Sasse Herrencreme', price: 17.0},
    {name: 'Sasse Herrencreme 200ml', price: 8.5},
    {name: 'Sasse Kakao mit Nuss', price: 20.0},
    {name: 'Sasse Kakao mit Nuss', price: 9.0},
    {name: 'Sasse Kräuterwacholder', price: 17.0},
    {name: 'Sasse Lagerkorn', price: 23.9},
    {name: 'Sasse Marille 0,5', price: 17.5},
    {name: 'Sasse Milchkaffee', price: 17.0},
    {name: 'Sasse Milchlikör-Set', price: 12.0},
    {name: 'Sasse Naturlikör Sechser', price: 20.0},
    {name: 'Sasse Salzkaramell', price: 17.0},
    {name: 'Sasse Williams 0,5', price: 17.5},
    {name: 'Sasse Williams Birne', price: 27.5},
    {name: 'Sauerländer Gewürzapfel 0,35', price: 16.9},
    {name: 'Secret Garden Pinot Noir Gin', price: 42.0},
    {name: 'Secret Garden Wild Gin', price: 42.0},
    {name: 'Secret Garden Winter Gin', price: 42.0},
    {name: 'Tabu Absinth', price: 22.9},
    {name: 'Torres 15', price: 35.0},
    {name: 'Unterthurner Waldler', price: 27.5},
    {name: 'Unterturner Marille', price: 24.9},
    {name: 'Whitley Neill 0,7', price: 26.0},
    {name: 'Whitley Neill orig', price: 32.0},
    {name: 'Zirmol 0,7', price: 35.0}
  ],
  feinkost: [
    {name: 'Arrabbiata', price: 6.0},
    {name: 'Chutney Birne', price: 4.5},
    {name: 'Feigenchutney', price: 6.0},
    {name: 'Foie Gras de Canard', price: 19.5},
    {name: 'Forster Traubensaft rot', price: 5.9},
    {name: 'Forster Traubensaft weiss', price: 5.9},
    {name: 'Geiger Cider Rosé', price: 3.0},
    {name: 'Giusti 2 Medaglie d´Oro', price: 15.0},
    {name: 'Giusti 3 Medaglie d´Oro', price: 23.0},
    {name: 'Giusti 3er Set', price: 54.0},
    {name: 'Giusti Anforina 100ml', price: 18.0},
    {name: 'Giusti Banda Rossa', price: 58.0},
    {name: 'Giusti Calamaio 50ml', price: 12.5},
    {name: 'Giusti Perle', price: 11.5},
    {name: 'Giusti Saba', price: 13.0},
    {name: 'Giusti Vino riserva', price: 9.0},
    {name: 'Giusti weiss', price: 13.0},
    {name: 'Jalall d´or Schoko-Salz-Mandeln', price: 6.5},
    {name: 'Jalall d´or Tüte Erdbeeren/weiße Schoko', price: 7.0},
    {name: 'Jalall d´or Tüte Himbeeren', price: 7.0},
    {name: 'Jalall d´or Tüte Mandeln Zitronr', price: 6.5},
    {name: 'Jalalld´or Eine Handvoll Glück', price: 4.9},
    {name: 'Jalalld´or Feuer und Flamme', price: 6.5},
    {name: 'Jalalld´or Rauchmandeln', price: 6.5},
    {name: 'Jalalld´or Weinklang 1', price: 6.5},
    {name: 'Jalalld´or Weinklang 2', price: 6.5},
    {name: 'Jalalld´or Weinklang 3', price: 6.5},
    {name: 'Jalalld´or Weinklang 4', price: 6.5},
    {name: 'Johannsen Bernstein', price: 4.5},
    {name: 'Johannsen Rumtopf 370g', price: 12.0},
    {name: 'Johannsen Rumtopf 720g', price: 15.0},
    {name: 'Junipaero', price: 15.0},
    {name: 'Kalamata Oliven', price: 5.0},
    {name: 'La Campofilone Fettuccine', price: 7.0},
    {name: 'Les Indispensables', price: 21.0},
    {name: 'Les Sablés Poivron&Piment D\'espelette', price: 5.5},
    {name: 'Linteo Grillo', price: 8.0},
    {name: 'Madonna Vittorie Oli', price: 16.0},
    {name: 'Meerfenchel', price: 12.5},
    {name: 'Mulled Winter Punch', price: 5.9},
    {name: 'Nou alkoholfrei', price: 11.5},
    {name: 'Olivade noir a la truffe Toupine et Cabesselle', price: 5.5},
    {name: 'Olivenöl Garda DOP', price: 27.5},
    {name: 'Olivenöl Orange', price: 29.9},
    {name: 'Paprika Bruschetta', price: 6.0},
    {name: 'Paprika Chutney', price: 6.0},
    {name: 'Pasta Fungo Porcino', price: 5.5},
    {name: 'Pasta Limone e Pepe', price: 5.5},
    {name: 'Pesto alla Genovese V. Bartolomeo', price: 6.0},
    {name: 'Pesto Basilikum', price: 7.0},
    {name: 'Pesto Ibleo', price: 8.0},
    {name: 'Pesto Rosso', price: 7.0},
    {name: 'Phileos Olivenoel', price: 19.5},
    {name: 'Polla Basilikum-Pesto ohne Knoblauch', price: 5.5},
    {name: 'Polla Olia Extra Vergine Selezione', price: 12.0},
    {name: 'Polla Tomatensauce', price: 5.0},
    {name: 'Pomodorini Ciliegino', price: 3.5},
    {name: 'Potage Dubarry', price: 9.0},
    {name: 'PriSecco Apfelsinf.', price: 11.0},
    {name: 'PriSecco Apfelsinfonie 200ml', price: 4.5},
    {name: 'PriSecco Cuvée 15', price: 13.0},
    {name: 'PriSecco Cuvee 23', price: 13.5},
    {name: 'PriSecco Cuvée 23 200ml', price: 4.5},
    {name: 'Prisecco Cuvee Nr 25', price: 13.5},
    {name: 'PriSecco Rosenzauber', price: 11.0},
    {name: 'Prisecco Rosenzauber 200ml', price: 4.5},
    {name: 'PriSecco rotfruchtig', price: 11.0},
    {name: 'PriSecco Rotfruchtig 200ml', price: 4.5},
    {name: 'PriSecco Sommerbirne', price: 12.0},
    {name: 'PriSecco weissduftig', price: 11.0},
    {name: 'PriSecco weissduftig 0,2l', price: 4.5},
    {name: 'Quadrotti alla Pizza', price: 5.0},
    {name: 'Ratatouille', price: 6.0},
    {name: 'Rillettes de Canard', price: 6.5},
    {name: 'Rouille Sétoise', price: 6.0},
    {name: 'Salzzitronen', price: 15.5},
    {name: 'San Marzano Tomaten', price: 3.5},
    {name: 'Sardinen klein, geräuchert, in Olivenöl', price: 7.0},
    {name: 'Sardinen Nr.32', price: 10.0},
    {name: 'Sardinencreme', price: 4.5},
    {name: 'Sardines Quiberonnaise', price: 10.0},
    {name: 'Siegfried Wonderleaf', price: 19.5},
    {name: 'Simon Coll Milchschokolade', price: 9.0},
    {name: 'Sugo al Basilico Venturino Bartolomeo', price: 5.0},
    {name: 'Tapenade grüne Oliven', price: 4.5},
    {name: 'Taralli', price: 3.5},
    {name: 'Taralli mit Fenchel', price: 4.5},
    {name: 'Taralli mit Speck und Käse', price: 4.0},
    {name: 'Taralli Olio', price: 4.0},
    {name: 'Tartare gegrillte Paprika', price: 4.5},
    {name: 'Tartufini Dolce', price: 8.5},
    {name: 'Toupine et Cabesselle Confit d?oignons Cévennes', price: 4.5},
    {name: 'Toupine et Cabesselle Crème de Cèpes', price: 5.5},
    {name: 'Toupine et Cabesselle Pesto', price: 4.5},
    {name: 'Toupine et Cabesselle Poichichade à la coriandre', price: 4.5},
    {name: 'Toupine et Cabesselle Sardinade tomate et piment', price: 4.5},
    {name: 'Vaux Träublein', price: 10.0},
    {name: 'ViSecco Pinot Meunier', price: 15.5},
    {name: 'ViSecco Sauvignon Blanc', price: 15.5},
    {name: 'Wachtelei Bandnudeln', price: 6.5},
    {name: 'Wachtelei Wellennudeln', price: 6.5},
    {name: 'Wellpaero', price: 15.0},
    {name: 'Wildfürst Bolognese', price: 13.0},
    {name: 'Wildfürst Rehcurry', price: 13.0},
    {name: 'Wildhackbällchen Wildfürst', price: 13.0},
    {name: 'Wildschweinsalami', price: 8.0},
    {name: 'Zotz Blanc de Blancs Alkoholfrei', price: 12.0},
    {name: 'Zotz Creation Rosé', price: 11.0},
    {name: 'Zotz Creation Rouge', price: 11.0},
    {name: 'Zotz Grauburgunder Alkoholfrei', price: 12.0},
    {name: 'Zotz Sauvignon Blanc alkoholfrei', price: 12.0}
  ]
};
